name: 'Prepare Deployment'
description: 'Typescript action to prepare dictyBase software for deployment'
author: 'dictyBase'
inputs:
  clusterName:
    description: 'Name of Kubernetes cluster'
    required: true
  clusterZone:
    description: 'Kubernetes regional cluster'
    default: 'us-central1-a'
  chartName:
    description: 'Name of Helm chart'
    required: true
  chartPath:
    description: 'Path to Helm chart'
    required: true
  namespace:
    description: 'Namespace used in cluster'
    required: true
  imageRepo:
    description: 'Docker image repository'
    required: true
  imageTag:
    description: 'Docker image tag'
    required: true
  commitID:
    description: 'GitHub commit ID'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'blue'
  icon: 'truck'