name: 'Prepare Deployment'
description: 'Typescript action to prepare dictyBase software for deployment'
author: 'dictyBase'
inputs:
  cluster-name:
    description: 'Name of Kubernetes cluster'
    required: true
  cluster-zone:
    description: 'Kubernetes regional cluster'
    default: 'us-central1-a'
  chart-name:
    description: 'Name of Helm chart'
    required: true
  chart-path:
    description: 'Path to Helm chart'
    required: true
  namespace:
    description: 'Namespace used in cluster'
    required: true
  image-repository:
    description: 'Docker image repository'
    required: true
  image-tag:
    description: 'Docker image tag'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'blue'
  icon: 'truck'