name: Continuous integration
on: 
 push:
   branches:
     - develop
jobs:
  testpack:
    runs-on: ubuntu-20.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v1
        with:
            node-version: '12.x'
      - name: check out code
        uses: actions/checkout@v2
      - name: unit test 
        run: |
            yarn
            yarn test