name: "build-test"
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        yarn install
        yarn all
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        cluster-name: "testkube"
        chart-name: "testbot"
        chart-path: "deployments/charts/testbot"
        namespace: "dictybase"
        image-repo: "dictybase/testbot"
        image-tag: "test"
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}